### ISSUE TITLE
Handle Telegram/* edits on Matrix

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1015]
**Is your feature request related to a problem? Please describe.**

When a message is sent from Telegram to Matrix and edited, it appears at Matrix with the `(edited)` suffix rather than the original message getting edited.

**Describe the solution you'd like**

I would like Matterbridge to edit the message it has relayed, I think the specification is somewhere in https://matrix.org/docs/spec/client_server/r0.6.0

**Describe alternatives you've considered**

I don't see other alternatives than the current behaviour and this request.

**Additional context**
\-

**Comment by MayeulC** [comment]
Matrix has support for this, but it currently sits in https://github.com/matrix-org/matrix-doc/pull/1849 which isn't yet part of the spec. There is one notable difference with the current (temporary) implementation, in that `m.relationship` is currently `m.relates_to`. Otherwise, the implementation is as-described. Not sure if best to implement now or once the MSC is merged?

**Comment by Mikaela** [comment]
I think it may be better to wait

**Comment by Sorunome** [comment]
The MSC seems mostly stale currently? with little activity.

Clients do, however, already implement editing with `m.relates_to`. If that MSC goes through with `m.relationship` a change would be trivial to adapt it, though it is probably more likely that the MSC changes to `m.relates_to`.

**Comment by 42wim** [comment]
Fixed with #1286
