### ISSUE TITLE
Discord messages from webhook aren't passed to IRC

### ISSUE THREAD

**Issue by burner1024** [42wim/matterbridge#1027]
**Is your feature request related to a problem? Please describe.**
I'm not entirely sure whether this is a bug, or should be a feature request instead, or I'm just missing something in config.
The issue is that when a [github hook](https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks) sends a message to discord, it's not propagated to IRC (probably others, too, but my use case is this).
The log:
```log
matterbridge[17535]: time="2020-03-07T15:15:56Z" level=warning msg="Failed to fetch information for member &discordgo.User{ID:"642679184254173185", Email:"", Username:"GitHub", Avatar:"df91181b3f1cf0ef1592fbe18e0962d7", Locale:"", Discriminator:"0000", Token:"", Verified:false, MFAEnabled:false, Bot:true} on guild "420268540700917760": HTTP 404 Not Found, {"message": "Unknown User", "code": 10013}" prefix=discord
```
(The message is sent as an embed.)

**Describe the solution you'd like**
The message is propagated to other channels. (or maybe it should be configurable)

**Describe alternatives you've considered**
Creating a separate hook for each channel could be a workaround, but with number of channels growing it would become messy.

**Comment by qaisjp** [comment]
In my experience I've found that messages from other bots don't get synced. For example:

![image](https://user-images.githubusercontent.com/923242/76154110-a8381a80-60ce-11ea-8f0a-0d00bf5e446e.png)

![image](https://user-images.githubusercontent.com/923242/76154111-b0905580-60ce-11ea-9499-765f95ed05e0.png)

----

The logged message is because the user ID of the message is the webhook ID, and not an actual user. I think we can determine this by discriminator being `0000`.

i.e. your GitHub webhook should look like this: https://discordapp.com/api/webhooks/642679184254173185/some-token-here

**Comment by haykam821** [comment]
You need to enable embeds with the `ShowEmbeds` config option. I think the error is due to using the same bot account on multiple guilds’ bridges though.

**Comment by burner1024** [comment]
@haykam821 Oh, I totally overlooked it, thank you. I've enabled it and now everything works properly.

@qaisjp 
The warning message stays. I don't know if it's of any interest by itself. Please feel free to close if not. And apologies for misleading.

**Comment by qaisjp** [comment]
Perhaps ShowEmbed should default to true

@burner1024 I plan to submit a fix for the warning
