### ISSUE TITLE
Username "spoofing" for IRC

### ISSUE THREAD

**Issue by lambdadog** [42wim/matterbridge#1152]
Ideally, if one is privately hosting an IRC server that they want to mirror channels of to another chat protocol or set of chat protocols, some sort of username spoofing would be possible. Matrix does it, and so does `go-discord-irc` in this case.

**Describe the solution you'd like**
My ideal solution would be to support the TS6 bridging protocol. This is the protocol used by many modern IRC servers to bridge multiple servers into one network, and is also used by services packages such as Atheme and Anope. It's essentially a privileged IRC connection that allows support for multiple users over one connection and carries the high level of trust of being seen as a "peer" in status to the IRC server being connected to and would be the correct way to represent another linked chat server with multiple users connected IMO.

**Describe alternatives you've considered**
While TS6 is the ideal solution for private hosted servers, the other approach would be to just generate multiple connections, one per account, to the IRC server. This would allow usage with permission on servers that one didn't have full control over, but I would generally argue it to be less correct.

**Comment by jlu5** [comment]
I want to to chime in here because I've worked with [server-based IRC relays](https://github.com/jlu5/PyLink) for quite some time now, and this method isn't without its limitations.

Although TS6 is a pretty well-documented server-to-server protocol, the reality is that server protocols vary drastically between implementations. The [TS6](https://github.com/charybdis-ircd/charybdis/blob/master/doc/technical/ts6-protocol.txt) flavour that's most well known refers only to ratbox, charybdis, and their close relatives. Other IRCds like InspIRCd, UnrealIRCd, and Hybrid speak protocols similar to TS6, but different enough to be fundamentally incompatible. For this to work properly, you'd need to implement a separate transport for each IRCd you're interested in supporting.

But more broadly, my biggest issue with spoofing non-IRC platforms as an IRC server is that it requires a lot of state management under the hood to ensure a consistent experience. For starters, this forces every other bridge to track a complete list of users, and track people as they join or leave. This is #667 and a WIP as far as I can tell, but it naturally increases the minimum complexity for other bridges. Then there's the task of having to implement everything that an IRC server has to at the server level: kicks, kills, squits, modes, and all sorts of stuff. IRC in particular doesn't allow rejecting messages once another server sends it, so once you receive e.g. a kick, the bridge server just has to deal with it somehow. If the other end doesn't support per-channel kicks (e.g. on Discord), the best thing you can do is rejoin the user and possibly warn the sender. Same goes for /kill and even /squit, if you create virtual servers to represent each remote bridge. But overall, implementation details like these add up fast and make the bridge code a lot more complicated than it seems at first glance. 

The other approach you mentioned of creating new IRC connections for each user is what matrix-appservice-irc and go-discord-irc use. This has the benefit of working natively on most IRCds, but you now have the overhead of maintaining a gazillion redundant TCP connections...

Bridging on IRC is hard. Regardless of which route you use there's a lot of overhead required to keep track of who's connected where. Trying to link [other platforms to IRC](https://github.com/PyLink/pylink-discord) given all these constraints frustrated me enough to design a special command just for relay bots instead, which I've mentioned @ https://github.com/42wim/matterbridge/issues/667#issuecomment-634214165

**Comment by lambdadog** [comment]
I didn't see #667! I'll go ahead and close this issue, but I might look into using the overdrivenetworks forks for my own personal use for now as well. I was looking into using Charybdis but I'm definitely willing to be flexible about it.

**Comment by qaisjp** [comment]
Duplicate of #667
