### ISSUE TITLE
Disallow user tokens for discord bridging.

### ISSUE THREAD

**Issue by craftxbox** [42wim/matterbridge#1221]
**Is your feature request related to a problem? Please describe.**
Yes. Discord does not allow bots and other applications to be run on user account tokens via its guidelines..

**Describe the solution you'd like**
Remove the ability to enter `User <token>` as a token for discord bridging, in order to use a user's account.

**Describe alternatives you've considered**
Actively disallowing user tokens, which may be more complex.

Discord, In its guidelines, explicitly disallows the use of self-bots and user-bots (which this would qualify as the latter), and this feature should be removed as to not encourage people to do as such. There is no situation where a user would be incapable of using a bot account instead of a user account.

**Comment by haykam821** [comment]
I don't think explicitly removing them is necessary. It's fine to add a warning to the docs, but matterbridge shouldn't be the enforcer of Discord's Terms of Service. 

> Discord, In its guidelines, explicitly disallows the use of self-bots and user-bots

It also disallows spam, which matterbridge can do as well by flooding the API. This doesn't mean the API should be ratelimited or even removed. It just means the user shouldn't spam the API and break the Terms of Service by doing so.

> There is no situation where a user would be incapable of using a bot account instead of a user account.

In some cases the person who wants to bridge would like to appear as a normal account since they cannot add bots to the server.

**Comment by craftxbox** [comment]
> In some cases the person who wants to bridge would like to appear as a normal account since they cannot add bots to the server.

That limitation exists for a reason. It's explicitly against the terms of service, and isnt one of those 'oh yeah its against the tos but we dont care' things, they DO actively ban user/self bots

> I don't think explicitly removing them is necessary. It's fine to add a warning to the docs, but matterbridge shouldn't be the enforcer of Discord's Terms of Service.

It would be understandable if this wasnt an *explicit option in the code*, and that it could just be used in that fasion, but the problem is that it IS an explicit option, and is going to encourage people to do it regardless. A warning will not do.

**Comment by qaisjp** [comment]
> **Is your feature request related to a problem? Please describe.**
> Yes. Discord does not allow bots and other applications to be run on user account tokens via its guidelines..

Is there are a problem **you** are specifically experiencing?

**Comment by haykam821** [comment]
What benefit is there in the maintainers putting in the effort to explicitly disallow using a user token?

For context, here is the only matterbridge code related to user tokens:

https://github.com/42wim/matterbridge/blob/97545695257b30bcaf80e1b64bbed6cce2303be6/bridge/discord/discord.go#L67-L70

This seems to just change the token format to match [the requirements in the library](https://github.com/matterbridge/discordgo/blob/8d8906ce4b959dacabfefbad9bacf11b6ffd8035/discord.go#L35-L36), and per the comment I think the functionality is broken anyways.

> but the problem is that it IS an explicit option, and is going to encourage people to do it regardless. A warning will not do.

I don't see a problem with that. It's on the user if they break the terms of service of a platform and get banned.

**Comment by 42wim** [comment]
I don't really get why discord still allows this feature. If they don't want people to use it, they can disable it.

**Comment by xXBuilderBXx** [comment]
I agree with both sides but if removing 3 lines of code that stops people from using user tokens is pretty good imo.
If this project were to get warned or any rumors of abuse the blame would be shifted onto users forking the repo and editing back in the support for user tokens rather than blaming this repo.

**Comment by 42wim** [comment]
I'm going to close this.

I've added a warning on the wiki page, because that wasn't clear.
- https://github.com/42wim/matterbridge/wiki/Settings#token-
- https://github.com/42wim/matterbridge/wiki/Section-Discord-(basic)

See also https://github.com/bwmarrin/discordgo/issues/446 about this issue. If the discordgo library removes it, it'll also be gone in matterbridge.
