### ISSUE TITLE
Add Let's Chat, Riot.im, and Glip

### ISSUE THREAD

**Issue by anonsubmitter** [42wim/matterbridge#124]
[Let's Chat](https://sdelements.github.io/lets-chat/), [Riot.im](https://riot.im/), and [Glip](https://glip.com/) are noteable enough to be added, in my opinion.

Here is somewhat of an indication of their popularity:
[https://alternativeto.net/software/let-s-chat/](https://alternativeto.net/software/let-s-chat/)
[https://alternativeto.net/software/vector-im/](https://alternativeto.net/software/vector-im/)
[https://alternativeto.net/software/glip/](https://alternativeto.net/software/glip/)

**Comment by 42wim** [comment]
Hi, 

Thanks for your ideas!

* Let's Chat can already be used by using their xmpp gateway (https://github.com/sdelements/lets-chat/wiki/XMPP), but the community and development seems quite dead. But I'll add it to #28 so that people can vote for it.
* Riot.im is already available (they are using matrix)
* Glip seems dead (also no API only support for sending messages, not for reading messages)

Please use #28 to further discuss other bridges
