### ISSUE TITLE
Discord Avatar Spoofing does not work

### ISSUE THREAD

**Issue by Cknight70** [42wim/matterbridge#1350]
**Describe the bug**
Even with setting ``AutoWebhooks=true`` no Discord Avatars will be spoofed.

**To Reproduce**
I have Rocket Chat bridged to Discord. 
I have the exact same username on Rocket Chat as discord. 
I have set ``RemoteNickFormat="{NICK}"`` so that the name will appear exactly as it does on Rocket Chat which is the same as myself on Discord.

**Expected behavior**
The Bot should spoof my avatar 

**Screenshots/debug logs**
![image](https://user-images.githubusercontent.com/28763729/103469431-f8e5c780-4d21-11eb-9558-1fe67f24acc3.png)
![image](https://user-images.githubusercontent.com/28763729/103469438-1024b500-4d22-11eb-8d40-bc17b7387a9e.png)

**Environment (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Matterbridge version: version: 1.21.0 cf13fff7

**Additional context**
```
[discord.mydiscord]
Token="realtoken"
Server="realserver"
RemoteNickFormat="{NICK}"
AutoWebhooks=true

[rocketchat.myrocketchat]
Server="https://RealRocketchatserver.com"
Login="real@rocketchat.com"
Password="xxxxxxx"
PrefixMessagesWithNick=false
RemoteNickFormat="[{PROTOCOL}] {NICK} "

[[gateway]]
name="general"
enable=true

[[gateway.inout]]
account="discord.mydiscord"
channel="ID:realchannelid"
AutoWebhooks=true

[[gateway.inout]]
account="rocketchat.myrocketchat"
channel="#general"
```

**Comment by qaisjp** [comment]
Did this work in a previous version of matterbridge?

Your config is missing `UseLocalAvatar`, and afaik that settings is required for the functionality you're describing:

https://github.com/42wim/matterbridge/blob/16fde6935c83c21987a3cb4d65a2608ca14d0341/matterbridge.toml.sample#L849-L854

Nevertheless, this config comment mentions `WebhookURL`, so it's likely that it now checks for a setting that can never be set, and needs to be fixed. Caused by #1523.

**Comment by qaisjp** [comment]
I've just checked the code — "This only works if WebhookURL is set" really means "This only works for messages sent by webhooks".

I don't see any obvious issue — please can you check whether it works when you set the `UseLocalAvatar` setting?

```toml
[discord.mydiscord]
Token="realtoken"
Server="realserver"
RemoteNickFormat="{NICK}"
AutoWebhooks=true
UseLocalAvatar=["rocketchat"]
```

**Comment by Cknight70** [comment]
> I don't see any obvious issue — please can you check whether it works when you set the UseLocalAvatar setting on the Discord account configuration?

Setting `UseLocalAvatar` as you described did in fact fix it! I also removed the unnecessary `AutoWebhooks`

I initially used this page on the wiki which doesn't yet mention the new method of using webhooks and  `UseLocalAvatar` [https://github.com/42wim/matterbridge/wiki/Section-Discord-(basic)#usernameavatar-spoofing](https://github.com/42wim/matterbridge/wiki/Section-Discord-(basic)#usernameavatar-spoofing)

**Comment by qaisjp** [comment]
> Setting `UseLocalAvatar` as you described did in fact fix it! I also removed the unnecessary `AutoWebhooks`

Nice!



> I initially used this page on the wiki which doesn't yet mention the new method of using webhooks and `UseLocalAvatar` [42wim/matterbridge/wiki/Section-Discord-(basic)#usernameavatar-spoofing](https://github.com/42wim/matterbridge/wiki/Section-Discord-(basic)#usernameavatar-spoofing)

I've updated the docs on that page to include the new `AutoWebhooks` setting, and to clarify the avatar stuff. 

Let me know if it's helpful, if there's anything that needs clearing up, (and feel free to edit it if you can think of any improvements).

And please close this issue if you think your problem is resolved :D

**Comment by Cknight70** [comment]
Thank you very much. I appreciate this project a lot.
