### ISSUE TITLE
use Telegram usernames on IRC

### ISSUE THREAD

**Issue by wxl** [42wim/matterbridge#144]
Currently, when bridging IRC and Telegram, with

```
[general]
  RemoteNickFormat="<{NICK}>"
```

Everything looks good on the Telegram end, but on the IRC end `{NICK}` gets expanded to the first name of the user rather than their Telegram username. Perhaps this is because [public usernames are an option][1] rather than a requirement (though I've rarely found someone that doesn't have it). I think it would be wise to first check if a username exists and to use that. Barring that, it would be reasonable to use the first name.

The other advantage is that it would be easier for someone on IRC to alert the user on Telegram because Telegram will interpret the @username as a mentioned. This is more difficult when the user does not have a username because there's no syntactic sugar to indicate a mention. Certainly on the Telegram end, you can see the IRC nick so that's easy to deal with. It would be nice if it went both ways.

[1]: https://telegram.org/faq#q-what-are-usernames-how-do-i-get-one

**Comment by 42wim** [comment]
At the moment the code checks if a FirstName exists, use this. If it doesn't exist, try Username, if this doesn't exist the nick will be "unknown". 

I think I did it this way because a FirstName always exists, but a Username (like you point out) doesn't need to exist. 

I could make this an extra option for the telegram config, so that you can set your order preference.

**Comment by xenoguy** [comment]
That would be fantastic.  I'm using matterbridge between TG and Slack, and first name in TG isn't very useful.

**Comment by 42wim** [comment]
Added in master ```UseFirstName=false``` (default setting).
Reopen if still issues
