### ISSUE TITLE
Allow IRC connection to aquire primary nick via GHOST 

### ISSUE THREAD

**Issue by bd808** [42wim/matterbridge#1480]
**Is your feature request related to a problem? Please describe.**
Process A0 is attached to an irc channel. A restart is performed to update config or whatever. Process A1 attaches to the same irc channel before the IRC server has recognized that process A0 has disconnected. NickServ informs process A1 that it's desired nick is in use. girc appends an `_` to the nick and tries again. Process A1 ends up connected with this alt nick.

**Describe the solution you'd like**
NickServ on many IRC networks supports a `GHOST` command to allow an authenticated account to forcibly disconnect a stale session or impersonation attempt.
```
[04:48] -NickServ- ***** NickServ Help *****
[04:48] -NickServ-  
[04:48] -NickServ- Help for GHOST:
[04:48] -NickServ-  
[04:48] -NickServ- GHOST disconnects an old user session, or somebody
[04:48] -NickServ- attempting to use your nickname without authorization.
[04:48] -NickServ-  
[04:48] -NickServ- If you are logged in to the nick's account, you need
[04:48] -NickServ- not specify a password, otherwise you have to.
[04:48] -NickServ-  
[04:48] -NickServ- Syntax: GHOST <nick> [password]
[04:48] -NickServ-  
[04:48] -NickServ- Example:
[04:48] -NickServ-     /msg NickServ GHOST foo bar
[04:48] -NickServ-  
[04:48] -NickServ- ***** End of Help *****
```

I think it would be possible to install a custom `c.Config.HandleNickCollide` callback to trigger a `GHOST` command instead of the default alt nick generation procedure. See 
https://github.com/lrstanley/girc/blob/2cb73c37725553fc472a3b8050cddc28f2989c4b/builtin.go#L103-L112 for the callback usage in girc.

If the registered HandleNickCollide callback sent a `PRIVMSG NickServ GHOST <nick>` message and then returned the primary nick I believe (untested) that the A0 process would be evicted and A1 would gain its desired nick.

This feature should be behind a config setting, possibly something like `UseGHOST=true`

**Comment by themiron** [comment]
this behavior can be achieved with RunCommands:
```
RunCommands=["PRIVMSG NickServ GHOST <nick> <pass>", "PRIVMSG NickServ NICK <nick>", "PRIVMSG NickServ IDENTIFY <pass> <nick>"] 
```
sure, UseGHOST=true will be more friendly way, but different irc servers may have different syntax for ghosting...
what if to add some predefined/template variables support to RunCommands? like %Nick% and %Password%, so commands can be used as a template

**Comment by Mikaela** [comment]
As themiron said, NickServ commands aren't standardized and vary between Atheme, Anope, Hybrid, Ergo etc. so I don't think it can be standardized. I would improve their `RunCommands` a bit by instead using e.g. for LiberaChat:

`RunCommands=["PRIVMSG NickServ@services. :REGAIN <nick> <optional-password>"] `

* Specifying the services server ensures that the message is sent to real NickServ avoiding leaking password should someone else be using the nickname NickServ (~~freenode~~).
* `PRIVMSG` with multiple words requires multi-worded message to begin with `:`, otherwise only the first word gets sent.
* REGAIN performs ghost and changes nickname, while otherwise it would be necessary to use GHOST + RELEASE + NICK.
* Password is optional if the user is already logged in e.g. by SASL.

I got the server `services.` from running `/map`.

**Comment by qaisjp** [comment]
As described above, `RunCommands` is the way to go here.
