### ISSUE TITLE
Crashing on XMPP with a panic

### ISSUE THREAD

**Issue by singpolyma** [42wim/matterbridge#1529]
Running 1.22.3 my process started crashing today every few minutes with this:

```
panic: runtime error: index out of range [0] with length 0

goroutine 738 [running]:
github.com/matterbridge/go-xmpp.(*Client).Recv(0xc0001da6c0, 0xc000b71a40, 0x20107fe, 0x11, 0xc000b71908)
        /go/src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/go-xmpp/xmpp.go:794 +0x23ac
github.com/42wim/matterbridge/bridge/xmpp.(*Bxmpp).handleXMPP(0xc0001309c0, 0x0, 0x0)
        /go/src/github.com/42wim/matterbridge/bridge/xmpp/xmpp.go:275 +0xcc
github.com/42wim/matterbridge/bridge/xmpp.(*Bxmpp).manageConnection(0xc0001309c0)
        /go/src/github.com/42wim/matterbridge/bridge/xmpp/xmpp.go:225 +0x27f
created by github.com/42wim/matterbridge/bridge/xmpp.(*Bxmpp).Connect
        /go/src/github.com/42wim/matterbridge/bridge/xmpp/xmpp.go:52 +0x22a
```

I made no changes today.

**Comment by 42wim** [comment]
Seems to be something with the xmpp avatar. Can you disable avatar support on your xmpp server and see if it still crashes?

**Comment by Polynomdivision** [comment]
I just looked at the code and I think I know where the issue lies: It seems that all is good except for the fact that no items have been published. I.e., the avatar or avatar metadata node exist but no avatar has been published yet. I think that the fix should be fairly easy. I'll see when I have time.
