### ISSUE TITLE
Linking Slack threads to Discord threads

### ISSUE THREAD

**Issue by gIsForGravity** [42wim/matterbridge#1558]
**Is your feature request related to a problem? Please describe.**
Currently, when Slack users reply to a thread, in Discord you just get their message preceded by [thread] (and vice versa with Discord replies), instead of having a Discord thread linked to the Slack thread.

**Describe the solution you'd like**
When someone sends a message in a Slack thread, or creates a Slack thread, a Discord thread should be created to parallel the Slack one and the messages should be synced. Same with a Discord thread being created or a message being sent in a Discord thread.

**Additional context**
It's really awesome that Discord finally has a thread feature that can parallel Slack's, and I think this would be such an awesome use for it. Thanks for all the awesome work you guys do.

**Comment by 42wim** [comment]
You need to add `PreserveThreading=true` to your slack and discord config, it'll map slack thread replies on discord replies.
Discord threads and slack threads are different because the discords ones are ephemeral.

**Comment by noisymime** [comment]
@42wim This seems to be working ok for myself (`PreserveThreading=true` is set for both Slack and Discord) however 1 thing I noticed is that in Discord any replies that come in from Slack are sent from the Bot ID rather than the user as with normal messages. The users name is show on the next line, but you don't get the avatar and it's less clear as their name isn't bolded. Normal (Non-reply) messages work fine.

Not sure if this is expected behaviour or not, but thought I'd call it out. 

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/138502/152662072-4be0a4d8-3e05-4e81-afd2-38504299ab4e.png">

**Comment by 42wim** [comment]
Only webhooks can impersonate and we need webhooks and webhooks do not support replies.

https://github.com/discord/discord-api-docs/issues/2410#issuecomment-819899764
> Discord has said multiple times that webhooks replying to messages will never happen. Allowing replies would let webhooks access any message but this behavior only lets them access their own (which they could theoretically access anyway by caching sent messages).

and https://github.com/discord/discord-api-docs/issues/2251

So that's not something matterbridge can fix unfortunately.

**Comment by LookitheFirst** [comment]
@42wim for my group, working Threads is a more important feature than correct usernames on the bot user. Could we get this feature, but only when webhooks are disabled in discord?

**Comment by 42wim** [comment]
@LookitheFirst afaik it's just not possible, you can do a workaround by setting `PreserveThreading=false`

**Comment by greenlighttec** [comment]
Hello earlier it was mentioned that threads are ephemeral  (and therefore I assume what was meant is that the bridge won't be able to interact with them) however here is documentation from Discord on API v9 https://discord.com/developers/docs/topics/threads that indicates how Bots can interact with threads including receiving message and create events. At the very least we should be able to not lose messages that are occurring within threads. I would like to re-visit the original intent of this feature request, to Discord Threads mimic Slack threads. 

I'm thinking some  functionality that would be similar to this.
PreserveThreading=True
TreatReplyasThread=False <- added for backwards compatibility, where if this is not set, it'll continue behaving the way it does now

With both above set to true the following behavior should occur.

When a user replies to a message from the bridge in Discord, it responds in slack pre-pending the previous slack messages URL, slack will auto-expand this link and make it visually similar to the way Discord replies behave. If a user creates a thread in Slack or Discord it should create a thread on the other end, Discord should use the first 25 characters of the message as the title of the thread

At a minimum it would be great if we could treat Thread messages in Discord the same way Reply messages are when PreserveThreading is enabled, because right now we're losing those messages entirely.

One day I'll get around to learning Go and would be happy to contribute to this project that has helped a lot in my community :)
