### ISSUE TITLE
Matrix: rejected bot on join

### ISSUE THREAD

**Issue by jQrgen** [42wim/matterbridge#1633]
I miss clicked "reject" to join the bots room om Matrix network.

Noe I cannot setup the bridge because I cannot "join a room I have leaved"

This seems like a bug.

**Comment by 42wim** [comment]
debug logs please

**Comment by Mikaela** [comment]
I think this issue is invalid as Matrix doesn't have any specific bot type of bot accounts and I haven't experienced matterbridge creating rooms for me. 

Matrix doesn't permit joining empty rooms of 0 users and if the room is invite-only, the solution is to simply invite the account matterbridge uses again and either accept the invite as it or let Matterbridge accept/join it on start.

**Comment by 42wim** [comment]
@Mikaela thanks for the comment, I'm going to close it.
