### ISSUE TITLE
[Enhancement Request] Edited messages should edit across supported bridges

### ISSUE THREAD

**Issue by jheiselman** [42wim/matterbridge#223]
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
0.16.2-dev

### If you're having problems with mattermost please specify mattermost version. 
NA

### Please describe the expected behavior.
When a message indicates that it's an edited message and it is being forwarded to a platform that supports message editing, then it should edit the original message

### Please describe the actual behavior. 
A new message is created instead of editing the original message

**Comment by jheiselman** [comment]
I'm not sure how possible this is without using something sort of data store to keep track of messages, but I thought I'd start a discussion about it.

[Discord messages](https://discordapp.com/developers/docs/resources/channel#message-object) have an `edited_timestamp` property that contains a non-null value if the message has been edited.

[Slack messages](https://api.slack.com/events/message) have an `edited` property if they have been edited. Otherwise, the property will be missing.

**Comment by 42wim** [comment]
Yes, this would mean matterbridge will have to keep state (the api bridge already does this though in memory in a circular buffer).

But if you edit a message in the past that mattermost/slack/discord hasn't seen yet, it will not work.
This is something nice to have, but not feasible for me in the short term. Could be a december project though.

As always PR's / discussions about this are welcome.

**Comment by 42wim** [comment]
Ok, this is happening, mattermost <=> discord already works locally, not yet commited to master.

**Comment by 42wim** [comment]
@jheiselman  @jleclanche  

The current code (also binaries can be found on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion) adds support for in place editing of message send to gitter, discord, mattermost, telegram and slack. 

The only exception here is that edits made by a gitter user aren't relayed because gitter doesn't relay edits in the streaming api. Message sent to gitter (eg from discord) and edited on discord while appear also edited on gitter.

Also, matterbridge can only edit messages that are done while matterbridge is running. It doesn't edit messages created at the time matterbridge wasn't running.

Testing and feedback are appreciated.
