### ISSUE TITLE
[Q] Why is bot user recommended for mattermost?

### ISSUE THREAD

**Issue by ninja-** [42wim/matterbridge#253]
I see that using webhooks for mattermost backend is not recommended. 
Why?
When running on bot user, you can't override username and avatar and that looks ugly compared to slack's bot pipe, which does this just fine...

The downside for sure is that you can't run outgoing mattermost webhook with private channel...

**Comment by 42wim** [comment]
I added this because bot user is easier to setup for most users. And if it's easier to setup, there are less issues ;-)

Especially the ```WebhookBindAdress``` is giving some trouble (firewall, can't find right ip, etc ..)
Also webhooks aren't always available for users, and if they are it doesn't mean that override username is etc..
And the private channel part like you mention

Maybe I should nuance it a bit more, and specify that if you're an advanced user and know what you're doing webhooks are fine :-) I'm planning to make more "advanced" documentation on the wiki, but haven't got the time yet.

**Comment by ninja-** [comment]
Thanks, that's very useful info :)

**Comment by ninja-** [comment]
@42wim would it be possible to use incoming hooks for posting messages and the bot user for observing messages to forward? so that way we can have name & avatar override and use it with private channels?

**Comment by 42wim** [comment]
That is already possible now (slack, mattermost and discord bridges behave like that)

If you have configured username/password  (or token) and webhookURL it uses webhookURL for posting and username/password (or token) for receiving.

**Comment by ArchangeGabriel** [comment]
So would you say that bot + incoming webhook is the best setup for seamless integration?
