### ISSUE TITLE
Split messages that are bridged to IRC to avoid <message clipped>

### ISSUE THREAD

**Issue by BFlorry** [42wim/matterbridge#281]
Would it be possible to split long one line messages that are sent to IRC by matterbridge? We have had multiple occasions where a person is writing a whole bunch in Discord and then the message gets clipped. I believe this would not trigger the flood-kick, but haven't been able to figure this out by myself.

Functionality would be as following:
Discord:
`[John]: This is a long message`
IRC:
`<Bot> [John]: This is a...`
`<Bot> [John]: ... long message`

Here's the message clipping functionality as defined in changelog:

> Maximum length of message sent to irc server. If it exceeds <message clipped> will be add to the message.

**Comment by 42wim** [comment]
If we don't do a 1:1 with the newlines, it'll be possible that you get so much messages from discord to irc that irc will never be able to catch up. 

It'll not flood because there's antiflood in the irc bridge

I'll think about adding a split option, but you'll have to live with the consequences if enabled ;-)

**Comment by 42wim** [comment]
`MessageSplit` added

```
#Split messages on MessageLength instead of showing the <message clipped>
#WARNING: this could lead to flooding
#OPTIONAL (default false)
MessageSplit=true
```
