### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#292]
Would it be possible to cut a new release? :)

**Comment by 42wim** [comment]
Next release will be 1.4
See https://github.com/42wim/matterbridge/projects/8 

If you need binaries of dev releases, you can get those on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion

**Comment by patcon** [comment]
ThanksMay I contribute to helping to improve the release process so that it's simple and can just be released on each new merged PR? If we can get it down to a simple tag-push-auto-minor-release, then there's no need to make anyone wait, no? I mean, I love kanban as much as the next person, but i'm not sure we're tied to it for release cycle :)

**Comment by 42wim** [comment]
There's an automatic release on each commit already, the latest on https://bintray.com/42wim/nightly/Matterbridge/_latestVersion and complete list on https://bintray.com/package/files/42wim/nightly/Matterbridge?order=desc&sort=fileLastModified&basePath=&tab=files

Doing a real release on every PR is a bit overkill I think, anyone who wants can run the binary dev release or rebuild it themselves. 

I'm doing 1.x.0 to 1.y.0 releases when major features have been added.
1.0.x to 1.0.y for critical and or small bugfixes

The kanban thing is to have some kind of "roadmap" so that I know what to work on, it's not really tied for the release cycle, things can and will get moved to a next release :)

The next release is close, i'm testing the new girc branch (https://github.com/42wim/matterbridge/tree/girc) to see if it's stable enough to be merged in for release.

**Comment by patcon** [comment]
Was adding this as an edit, but since you are so goddamn prompt:

> EDIT: Having said that, I understand the need to guard your time. Just wondering whether you can conceive a possibility where it might not consume more time :)

And one more thought: I am 100% appreciative if all the build magic you have in place so far! But while you see "overkill", I see something that would save the next person like me several hours of work and a a couple days of general upset at technology within our chat :) For someone like myself, who is eager to get certain critical features but not go-savvy, this takes awhile. (All our links were broken across the bridge in our slack chat with hundreds of academics who are relatively non-technical.)

I would love to be able to make that not a thing for the next person in my positive, but only if it's not detrimental to the flow from your perspective :smiley: (the above is to try to convey that your overkill is another's _super-helpful_ process change!)

**Comment by 42wim** [comment]
I understand you would want to test it as quickly as possible, but I don't understand why the dev build doesn't fix this issue for you ?

Is it because it is/wasn't easy to find ? some other reason ?

Could you explain this a bit more ?:)

(i'm off to bed now, so the promptness will end ;-)

**Comment by 42wim** [comment]
release has been cut 🎉

**Comment by patcon** [comment]
PS, i think I can resolve my concern with a change to the README, so i'll retract :)
