### ISSUE TITLE
matrixbot should not be added to gitter channel.

### ISSUE THREAD

**Issue by wsdjeg** [42wim/matterbridge#318]
you Can check our SpaceVim channel. when enable gitter / matrix / irc

there are two bots in gitter channel. one is set by gitter and another I do not know where it comes from.

gitter.im/SpaceVim/SpaceVim

**Comment by wsdjeg** [comment]
and message send from matrix will be display as

```
[gitter] <matrixbox> `name@matrix.org` : message

```

in irc

**Comment by wsdjeg** [comment]
the Bot should be owned by the channel. matrixBot is not main, message from matrix should be send to gitter by gitter's bot.

**Comment by 42wim** [comment]
I don't understand the question, what is the problem exactly?

**Comment by wsdjeg** [comment]
@42wim the problem is that, when I set:

```
[matrix]
    [matrix.mymatrix]
    Server="https://matrix.org"
    Login="wsdjeg"
    Password="***********"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
```

and 

```
[gitter]
    [gitter.mygitter]
    Token="a92d828fe41843fc579675c995829af3196c959e"
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
````

the gitter token is from `SpaceVimBot`, but when someone send message in matrix channel, in gitter, the message is not bridged by `SpaceVimBot`, but instead, it is comes from `matrixbot`.

**Comment by wsdjeg** [comment]
and  can you join our channel to see the message? I think you will find why I think it is a issue.

**Comment by thrrgilag** [comment]
@wsdjeg it's happening because someone bridged your gitter room to matrix using the matrix-appservice bridge hosted by matrix.org.  I did a quick search of the directory and see someone 6 users joined to a matrix room that is bridged that way.  If you want to stop it tell those users the correct matrix room to join and kick/ban the bot.  You can also find a matrix.org admin to see if they'd unlink the room and clear it from their directory.

**Comment by wsdjeg** [comment]
@thrrgilag can you have a try with join our matrix room and send a message? the matrix room is #spacevim:matrix.org
