### ISSUE TITLE
[Feature] (Telegram) Convert nicks automatically into HTML when MessageFormat is set to HTML

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#378]
I just recently got a problem, where i only could send messages in one direction and i (with the help of Wim) found out that Telegram seems to have a problem with special cars in nicks, when messages are send in HTML.

**Comment by 42wim** [comment]
Please test :)

**Comment by TomTheDragon** [comment]
I tested it and it seems to work so far now. Thx again.

**Comment by alphachung** [comment]
(I think because of this change) In 1.9.0, if `RemoteNickFormat` has HTML formatting, it shows the html tags instead of being parsed. It works in 1.8.0 but not 1.9.0. 

Config is:
`
[discord]
    [discord.twodee]
    Token="(token)"
    Server="(server name)"
    ShowEmbeds=false
    RemoteNickFormat="**<{NICK}>** "

[telegram]
    [telegram.tg2d]
    Token="(token)"
    MessageFormat="HTML"
    RemoteNickFormat="<b>&lt;{NICK}&gt;</b>\n"
    ReplaceNicks=[["",""]]

[[gateway]]
name="general"
enable=true

    [[gateway.inout]]
    account="discord.twodee"
    channel="general"

    [[gateway.inout]]
    account="telegram.tg2d"
    channel="(id)"


[[gateway]]
name="2d"
enable=true

    [[gateway.inout]]
    account="discord.twodee"
    channel="(channel name)"

    [[gateway.inout]]
    account="telegram.tg2d"
    channel="(id)"
`

In 1.8.0 it shows up in telegram as:
![image](https://user-images.githubusercontent.com/5276387/37557252-c1137a2e-2a3c-11e8-92cf-2c342dc1fecb.png)

But in 1.9.0:
![image](https://user-images.githubusercontent.com/5276387/37557255-ccbf4d94-2a3c-11e8-8c03-bab039f5d473.png)

**Comment by 42wim** [comment]
Seems like it's better to revert this patch.
And that people use your example `RemoteNickFormat="<b>&lt;{NICK}&gt;</b>\n"` if they want to support HTML
