### ISSUE TITLE
Incorrect handling of unpinning a message.

### ISSUE THREAD

**Issue by akhmerov** [42wim/matterbridge#388]
### Environment

Matterbridge version 1.5.1, mattermost version 4.6.0

official docker image, gitlab omnibus mattermost.

### Please describe the actual behavior. 
Unpinning a message from channel resulted in matterbridge relaying the message to gitter chat.

Expected result: no action.

### Any steps to reproduce the behavior?
Create a bridge mattermost <-> gitter, post a message in mattermost, pin, unpin

**Comment by 42wim** [comment]
Hi, please upgrade to latest master (https://bintray.com/42wim/nightly/Matterbridge/v1.8.0-47-ge5989ad) or 42wim/matterbridge:latest on docker

I can't reproduce this, but if you still can after upgrading, please run with `-debug` and repeat the actions.
Thanks!

**Comment by akhmerov** [comment]
I reproduced the issue on 1.8.0. I also noticed it only works once per pinned/unpinned message. Sorry for a newbie question, but how to pass `-debug` argument to the container?

FWIW, we are interfacing mattermost via a bot user rather than via API.

**Comment by 42wim** [comment]
Did you try 1.8.0 or the latest build? what does `matterbridge -version` show ?

**Comment by akhmerov** [comment]
I tried the latest build from docker hub (cfe6f82804b7)

**Comment by 42wim** [comment]
could you give me output of `docker run --rm -ti 42wim/matterbridge:latest -version` ?

**Comment by akhmerov** [comment]
`version: 1.8.1-dev e5989ad`

**Comment by 42wim** [comment]
Ok, I guess you run the docker build with something like this:
`docker run -ti -v /tmp/matterbridge.toml:/matterbridge.toml 42wim/matterbridge`

to run with debug do
`docker run -ti -v /tmp/matterbridge.toml:/matterbridge.toml 42wim/matterbridge -debug`

This will give you console output

Can you then do a mattermost message, pin it, unpin it and paste the complete debug output here or on pastebin, normally the debug output shouldn't contain any tokens or passwords.

**Comment by akhmerov** [comment]
Thanks! [Here goes](https://pastebin.com/e0cwGJ8F)

**Comment by 42wim** [comment]
Thanks for the feedback.

I've been looking into this and unfortunately there is nothing I can do, the pinned messages receiving from mattermost are exactly the same as edited messages, which means I can't differentiate them and can't filter them.

The pinned and edited messages contain a is_pinned bool that can be true or false, if I filter on is_pinned = true this means that edited pinned messages won't relay, and if I filter on is_pinned is false this means that normal (unpinned) edited messages won't relay.

This also means that bridges like gitter will only receive them once because they have editing support, an irc bridge will receive the message 3 times if you type a message, pin it and unpin it.

**Comment by akhmerov** [comment]
Ah, but OTOH every message starts unpinned. Perhaps it would be preferable to filter by not pinned messages?

**Comment by 42wim** [comment]
Yes, but this means that you will lose pinned messages that gets edited.

**Comment by akhmerov** [comment]
Indeed, it's probably the best to keep the current behavior.
