### ISSUE TITLE
Proposal: share link if file size > max download size

### ISSUE THREAD

**Issue by akhmerov** [42wim/matterbridge#395]
I love that the new matterbridge also relays the files. However when the files exceeds `MaxDownloadSize`, matterbridge posts `<system> file _filename_ too big to download (1247245 > allowed size: 1000000)`.

I believe in that case it would be better to fallback to the previous behavior of sharing the download link.

**Comment by 42wim** [comment]
Well, the idea is that link sharing is disabled on bridges that don't have public links. 

Receiving an image from mattermost, slack, matrix or telegram will do an upload instead of link-sharing, because those links are behind login/pass

Receiving an image from discord or gitter will sent a link (because those links are public)

**Comment by akhmerov** [comment]
> Receiving an image from mattermost, slack, matrix or telegram will do an upload instead of link-sharing, because those links are behind login/pass

Wait, I thought mattermost ones are public links? At least that's how it worked in previous versions of matterbridge. Was it changed recently in mattermost?

**Comment by 42wim** [comment]
I think by default public links are not enabled (https://docs.mattermost.com/administration/config-settings.html#public-links). 

In any case, matterbridge has no way to check if public links are enabled or not, so it's better to make sure it works for everyone by downloading files and reuploading them if possible. (maybe there could be an extra knob for people who know what they're doing so that they can disable this behaviour)

**Comment by akhmerov** [comment]
I see, thanks for the explanation. In that case the current behavior makes more sense.
