### ISSUE TITLE
Matrix webhook support

### ISSUE THREAD

**Issue by MayhemBill** [42wim/matterbridge#553]
**Is your feature request related to a problem? Please describe.**
I don't really like how it sends the messages, it looks kinda gross when they show up.
**Describe the solution you'd like**
use of webhooks so it can look a bit more native when messages are sent
**Describe alternatives you've considered**
I''ve tried a variety of plugins for Minecraft and Discord and they seem to either not do what I want, or can't read other webhooks.
**Additional context**
Discord Example
![aicher](https://user-images.githubusercontent.com/5598969/47971941-d8982080-e064-11e8-8755-85912952f60d.PNG)

**Comment by NikkyAI** [comment]
discord does have webhook support for discord, you have to set the individual webhook urls on each channel in the gateway config,
unless there is some other meaning of webhook related to discord i am not aware of?

since its dealing with minecraft, matterlink also supports user avatars rendered by visage

**Comment by patcon** [comment]
Can you explain what I'm looking at in that screenshot? Like are you saying that "Aicher" is the name of the bot, and not the user who sent the message? And is that avatar not specific to the user who sent the message?

Thanks for clarifying -- I don't use discord, but am curious about your support request

**Comment by NikkyAI** [comment]
the avatar will obviously only change if matterbridge sends a essage from another service that has avatars.. so if this is irc -> discord it will not pass along a avatar url

**Comment by patcon** [comment]
Thanks @NikkyAI. @MayhemBill but if there's anything else specific about the formatting that you think would improve it, definitely clarify that :)

Without more information that's more specific and actionable (since the avatar thing isn't something we can fix), this issue will probably be closed out without more info :)

---

But as an aside, matterlink could perhaps do some sort of lockup against another website's list of usernames, and use that. So if the username is the same, then it could send that avartar url instead?

It might also be possible to address this in Matterbridge, but not sure if @42wim would see it in scope. Basically, for incoming messages from services without avatar support, it could do the username lookup from the list of users on another protocol, and match with that. Some version of config like this (although this might not be the best config format)

```
[[gateway]]
name="mychannel"
enable=true
  [[gateway.inout]]
  account="slack.myteam" # avatars: yes
  channel="mychannel"
  [[gateway.inout]]
  account="api.local" #avatars: no (unless sent in message POST from outside, ie. matterlink)
  channel="api"
    [gateway.inout.options]
    AvatarLookupAccounts=["slack.myteam"]
  #[[gateway.inout]]
  #  account="irc.irc" #avatars: no
  #  channel="#mychannel"
    [gateway.inout.options]
    AvatarLookupAccounts=["slack.myteam"]
```

**Comment by MayhemBill** [comment]
Aicher is the username of the player on Minecraft (we're currently using another plugin to bridge minecraft to discord)
And the avatar is that of Aicher, I'd like it to sort of mimic the users avatar and name, to create a more streamlined conversation, instead of messages coming from a bot and being all bunched together

**Comment by MayhemBill** [comment]
Ah I started reading more into the advanced config and found that it is possible for Discord, but can that be used for Matrix as well? so that they show up the same way across all platforms?

**Comment by patcon** [comment]
Seems that the Discord API doesn't let bots change their name or avatar on a message by message level, so that I think that's mostly the best you can get.

Alternatively, it would be a bit spammy (because attachments prob take up more room, but maybe you could figure out a way that attachments might be a helpful work-around: https://discordapp.com/developers/docs/resources/channel#create-message-using-attachments-within-embeds

If you're seeing it for discord, it's probably that users can authenticate another service, but I don't think that's possible -- matterbridge is designed to only pretend to be one user, often a bot user. It just happens that some platforms let that user put on a bunch of different nicknames and avatars. Matrix and discord don't allow that.

> Ah I started reading more into the advanced config and found that it is possible for Discord

(You may be reading about having users oauth authenticate on a one-by-one level, but that's not how matterbridge currently works, unfortunately 😞 )

**Comment by MayhemBill** [comment]
Sorry I may have done a poor job at explaining what I was looking for, when using webhooks, it allows to set the avatar and the username of the webhook, from what I can tell, Matterbridge can do this on Discord, I'm looking for that to be done on Matrix as well. 

An example is included
![webhooks](https://user-images.githubusercontent.com/5598969/48012455-04acb380-e0f0-11e8-8aa0-2cab39af4d50.PNG)
It makes it look like it's an actual user sending messages, but it's just a webhook. 

I have done this manually on Matrix, so I know it is possible to be replicated, I just don't know if Matterbridge can do it on Matrix.

**Comment by patcon** [comment]
ah okie doke, gotcha i think :)

Maybe with this: https://t2bot.io/webhooks/ (it's open source, but happens to have a hosted instance, which is nice for testing)

**Comment by MayhemBill** [comment]
That's what I'm using for my webhooks, but does Matterbridge support it, and more or less how would I set that up in the config?

**Comment by NikkyAI** [comment]
actually what zou want is handled by matterlink when matterbridge is using webhooks

webhooks can send a username and avatar per message (bots cannot)

**Comment by MayhemBill** [comment]
But that's a minecraft mod, I'm just looking to know if Matter bridge supports webhooking messages to Matrix?

**Comment by patcon** [comment]
Maybe try investigating the webhook logic for mattermost or slack and see if you can bring it into matrix?

## Mattermost

https://github.com/42wim/matterbridge/blob/b81ff9c008ed3084c6bf2d6fe6bfbc077546d6ac/bridge/mattermost/mattermost.go#L376-L417

## Slack

https://github.com/42wim/matterbridge/blob/b81ff9c008ed3084c6bf2d6fe6bfbc077546d6ac/bridge/slack/slack.go#L187-L245

**Comment by MayhemBill** [comment]
I don't know much about GO, but I do know that when using turt2live's webhooks, they work just like slack. 

the github here: https://github.com/turt2live/matrix-appservice-webhooks

**Comment by patcon** [comment]
If you feel like taking a run at it, I'm happy to review and answer questions

**Comment by 42wim** [comment]
@MayhemBill so you got it working for discord right?

Regarding to matrix, as far as I understand Matrix doesn't support those features unless you're running your own homeserver.
Could you explain how you use turt2live's webhooks? Are you running your own homeserver?

**Comment by MayhemBill** [comment]
It works for discord, and the webhooks run through an app service. They function exactly like Slacks webhooks do. (IE, You post the same way you would for Slack) So it's just a matter of copying the Slack webhook code to matrix and then making that work together.

Also I am running my own homeserver, but Turt2live has a bot running publically that can be invited to your Matrix room (how I'm using it for now)

**Comment by 42wim** [comment]
Ok, i'm going to close this in favor of #137 
If I (or someone else) implements the AppService it should be possible.
