### ISSUE TITLE
[Slack] Allow auto-joining of room if accessible via token

### ISSUE THREAD

**Issue by patcon** [42wim/matterbridge#651]
I think this code-path may have accidentally gotten a little zealous? Using both slack and slack-legacy, it prevents account from joining rooms, regardless of whether token has ability to join.

https://github.com/42wim/matterbridge/blob/a2754f15fc2bc2eede94e2e41712f9f0585f2426/bridge/slack/slack.go#L175-L177

Could we add a simple bridger check based on the token prefix, so that we instead have something like:

```go
	if b.CanJoinChannels() && !channelInfo.IsMember {
		return fmt.Errorf("slack integration that matterbridge is using is not member of channel '%s', please add it manually", channelInfo.Name)
	}
```

**Comment by patcon** [comment]
user token. they can't auto-join anymore after https://github.com/42wim/matterbridge/commit/6238effdc27e4f439cb49bfa5fb5cd09fd88375e#diff-9cf086abe9322e8e54948ce48e302166

**Comment by Helcaraxan** [comment]
Late comment: you shouldn't be using a user token to bridge your Slack.

The removal was intentional though. 😉 

If OK with you I would close this issue @patcon.

**Comment by patcon** [comment]
To be candid, I find this was a bit disingenuous @Helcaraxan. My understanding was that the idea behind legacy was to _not_ impose the controversial view you had on others. This feels like one of those small breaches of trust to hear that you intended to do this after all those conversations.

**Comment by Helcaraxan** [comment]
Hello @patcon. Thank you for sharing your perspective. Much appreciated and very helpful. ❤️

In all honesty it was not my intention to be disingenuous and I offer you my apologies if I have made you feel that way. Given my PR that you referenced I can definitely understand your interpretation of things, no question there. As it stands I did not explicitly think of the `legacy-slack` bridge when I wrote that PR. So there was no deliberate intention to break things for legacy users. I am aware that my follow-up comment that I posted above before closing the issue does not seem to square with that: I did not take the appropriate time at that time to properly review the issue and it resulting from my PR. Again, my apologies.

On the principle I do stand by the response I gave: _"you should no longer be using user tokens"_. Not because I personally don't want you too, but because it doesn't fit with the evolution of Slack's own product direction. I very well understand the use-cases of this workflow. Heck, I would actually love to use it myself in my own Matterbridge deployment, although in my specific case I can also work fine without it. I would encourage you and other users to give your feedback to Slack itself and their Product Managers: that you want / need this feature, so that they might build it into their new approach to permissions.

That said I should definitely not have broken the behaviour unnecessarily as I did. I will try to get up a PR to re-establish the desired behaviour for legacy bridges.

**Comment by patcon** [comment]
Appreciate it. I was trying to assume good faith, as that's usually the case :) Fwiw, the auto-joining was one of the features that was explicitly valued for what I was working on (though the democratic, non-admin nature of creating user tokens was also a plus).

I humbly disagree with your principledness on this token thing. Their copy choices and language around deprecation is very much a result of the way they want the ecosystem to grow, due to their business needs and desire to lock things down for tiered plans. I feel you are playing into their cover-your-ass business-speak, while this feature will exist for quite some time and usefulness. Your personal decision to accommodate their business rationale, seemingly because it doesn't affect you so much -- this does not necessarily need to be a choice for you to make for everyone. That was my frustration.

(And talking to Product feels quite useless. It's evident why they're doing it, and it's related to capital that speaks louder than anything I have to say to them.)

Lastly, please don't worry about fixing it :) I would feel bad about that, as your time in precious, and I am not actively working on the piece that would benefit. I would truly appreciate your consideration for treading more lightly with deprecations and advisories in your future work -- esp business-related ones, unrelated to the pure pragmatism of FOSS library maintainers

I still think you're awesome. 🎉

**Comment by 42wim** [comment]
> That said I should definitely not have broken the behaviour unnecessarily as I did. I will try to get up a PR to re-establish the desired behaviour for legacy bridges.

I agree with this statement, this shouldn't break for existing legacy users.
I'll reopen this issue until the PR is here.
@Helcaraxan If you don't want/have time to fix this, let me know and I'll try to pick it up.
