### ISSUE TITLE
Slack - Use Full Name Rather Than Email

### ISSUE THREAD

**Issue by Rikairchy** [42wim/matterbridge#691]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, the first portion of the email address (prior to the domain) is used when the Display Name is empty on Slack.

**Describe the solution you'd like**
As a full name is required, I would like Matterbridge to rely on the Full Name rather than the first portion of the email when identifying users

**Describe alternatives you've considered**
Telling everyone to use set a Display Name. Unfortunately, this is not always reliable.

**Additional context**
Setting ```RemoteNickFormat="[{BRIDGE}/{CHANNEL} - {NICK}]: "``` results in the email being used if a display name is not set. Is it possible to select the full name from the user's profile on the workspace instead?

**Comment by Helcaraxan** [comment]
Hello @Rikairchy,

This would need to be a Slack-specific configuration to use the "Real name" instead of the normal "username" which is indeed the email without the domain if you have a Slack workspace requiring someone to possess an email within a specific domain.

If this were to be the default behaviour this would leak personal information: the email is part of a user's public profile but not their real name.
