### ISSUE TITLE
Races in `slack/helpers.go`

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#759]
**Describe the bug**
I believe there are races around the `b.users` usage in `slack/helpers.go`. Let me explain:

Let's look at `getUser` function
https://github.com/42wim/matterbridge/blob/57f156be8328529666aadaee780711f12b6e162b/bridge/slack/helpers.go#L14-L26

- Line 15 : the lock is set , that's good, other threads wait ..
- Line 16 : we are checking if the user is set, so far so good
- Line 17 : the lock is released (I believe it shouldn't)
- Line 18: let's assume the user is not set `ok == false`
- Line 21: we are populating user

Now another thread enters, the lock is not set (we unlocked in line 17), gets a lock, checks if the user is set on line 16 (it is not) and jump also into populating user in Line 21. 

The locks should be used to guard bigger chunks of logic, many lines, that needs to be invoked separately from other threads. Here, I believe that the whole function should be guarded as such:

```go
 func (b *Bslack) getUser(id string) *slack.User { 
 	b.usersMutex.RLock() 
        defer  b.usersMutex.RUnlock() 

 	user, ok := b.users[id] 
 	if ok { 
 		return user 
 	} 
 	b.populateUser(id) // BTW populate could be returning the user
        return b.users[id] 
}
```
----

Same goes for populateUser:
https://github.com/42wim/matterbridge/blob/57f156be8328529666aadaee780711f12b6e162b/bridge/slack/helpers.go#L73-L77

**Comment by Helcaraxan** [comment]
I can (partially) answer your question given that I wrote the original version of these functions.

---
For the `populateUser()` method:
The two locks that are used are different: the first is a read-only lock, the second a read-write lock. 

The RW lock is not covering a bigger chunk of the logic as that would contain the call to the Slack API for which there is no guarantee of the time that it will take. It also does not touch the actual `users` map.

For the `getUser()` method:
The split in two lock sections is a requirement due to the call to the `populateUser()` method which will need to lock itself. Hence the `getUser()` method needs to release the lock first before calling. Note as well that `getUser()` uses read-only locking and not RW locking.
---

I do understand the concern behind your question and I have a solution to the stacking of `populateUser()` calls. I'll put up a PR for it in a short while. It will complicate the logic a bit further but I'll do some refactoring to keep it manageable.

**Comment by KrzysztofMadejski** [comment]
> **`getUser()` method**
> 
> The split in two lock sections is a requirement due to the call to the `populateUser()` method which will need to lock itself. Hence the `getUser()` method needs to release the lock first before calling. Note as well that `getUser()` uses read-only locking and not RW locking.

I had a bit of argument in go repo about how mutexes behave: https://github.com/golang/go/issues/30657 but I didn't convince go developers.




> I do understand the concern behind your question and I have a solution to the stacking of `populateUser()` calls. I'll put up a PR for it in a short while. It will complicate the logic a bit further but I'll do some refactoring to keep it manageable.

I don't know what solution you are planning, but I just thought that a good go-way would be to 
1. send "asks to populate user" in a dedicated channel
2. create several "populators" that would read those asks , check if others are not working on it (initial mutex) and call slack to populate
3. populators would signal back through different channel that the finished populating user X; those who send those asks would wait on those signals.

BTW: I don't believe that reading and writing to `b.users` on one line needs to be guarded by mutexes: this is an atomic operation.

**Comment by Helcaraxan** [comment]
Thank you for the pointer to the Go repo discussion that you raised. Always useful for context. 🙂 

With regards to the solution I am planning to choose: it's actually almost exactly to what you are suggesting. You can check the full work in the last 3 commits of Helcaraxan/matterbridge@b280160c1efb5e5de84b16da51ec20ca813d85af, with the last commit containing the actual fix (the first of the three is the one for this PR).

Reading and writing to `b.users` does need to be guarded by mutexes as the standard `map` type [is not thread-safe](https://golang.org/doc/faq#atomic_maps). For that we would need to use `sync.Map` but that type is too heavy and specialised for our use-case as per [its own documentation](https://golang.org/pkg/sync/#Map).

**Comment by KrzysztofMadejski** [comment]
You learn something every day :D. I edited my previous message adding hesitation to the map is atomic statement.
