### ISSUE TITLE
Migrating mulit-channel, multi-token mattermost configuration to newer version

### ISSUE THREAD

**Issue by ctron** [42wim/matterbridge#782]
In the past it was possible to use multiple mattermost outgoing channels like this:

~~~
[mattermost]
url="https://mattermost.eclipse.org/hooks/1234"
port=9999
BindAddress="127.0.0.1"

[Token "234"]
IRCChannel="#foo"
MMChannel="bar"

[Token "456"]
IRCChannel="#bar"
MMChannel="baz"
~~~

I don't see any example about this in the new configuration. What would be an appropriate configuration for this?

I don't want to use personal access tokens, as this, at least to my understanding, would no longer allow to replace the nick in mattermost. Current it is "irc-<irc-nick>", using a personal access token it would always be the user of the token.

**Comment by 42wim** [comment]
I don't even remember that config anymore, according to the changelog it's from < v0.4 :)

You can mix personal tokens and webhook urls though, it'll use the personal token for the matterbridge inbound messages (so that you don't need a BindAddress anymore) and it'll use the webhookURL for sending messages, so you can still replace the nick.

The config has changed quite a bit, I suggest you follow https://github.com/42wim/matterbridge/wiki/How-to-create-your-config
You can also ask questions on our bridged chats, see the `README.md` on how to join.

**Comment by 42wim** [comment]
Closed because inactive, reopen if still applicable.
