### ISSUE TITLE
Does chat support have to built into the matterbridge binary?

### ISSUE THREAD

**Issue by jakubgs** [42wim/matterbridge#880]
If I wanted to develop bridging functionality for https://status.im/, would that have to be built into MatterBridge itself, or could it have a form of a library loaded on runtime?

I couldn't find any clear instructions on how to extend MatterBridge with your own chat support, but from what I've gathered the only way is to fork MatterBridge and add that functionality to its codebase. Is that right?

**Comment by Helcaraxan** [comment]
Hello @jakubgs.

There are two ways in which Matterbridge can support a new protocol:
- You can, as you already suggested, build it into the binary by adding [native support](https://github.com/42wim/matterbridge#natively-supported) for the targeted chat protocol. Instead of using a fork it would be encouraged to contribute this new native support to the core repository via one or more PRs. **Before** going down this road **please do discuss** the way in which you would add support first: third-party libraries you will depend on, expected maintenance burden (based on the stability of the protocol and it's library), etc.
- You can use [the Matterbridge API](https://github.com/42wim/matterbridge/wiki/Api). This is a REST endpoint that is exposed by the Mattebridge binary, if configured to do so. You can then write your own independent binary / bot-client that "bridges" between the targeted chat protocol and Matterbridge. There are already a few of such [third-party "plugins"](https://github.com/42wim/matterbridge#3rd-party-via-matterbridge-api).

**Comment by qaisjp** [comment]
> or could it have a form of a library loaded on runtime

This could be achieved using plugins: https://golang.org/pkg/plugin/

**Comment by 42wim** [comment]
https://github.com/42wim/matterbridge/wiki/Gateway:-developing-new-one is also a helpful page

@jakubgs regarding `JoinChannel` some protocols need to bot to be joined by the `admin` so they don't need or can't join the channel themselves. 

Maybe the xmpp one is a bit simpeler: https://github.com/42wim/matterbridge/blob/942d8f1cedfb7325c0720f8967751bb1b77f5b82/bridge/xmpp/xmpp.go

Wrt how you get messages, most of the bridges run a for loop in a go routine on a successfull Connect() which receive the messages from the server and send them into matterbridge using the `Remote` message channel.
